// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RFIDify.Database;

#nullable disable

namespace RFIDify.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240130003312_AddSpotifyCredentials")]
    partial class AddSpotifyCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("RFIDify.Spotify.Data.SpotifyCredentials", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("SpotifyCredentials");
                });
#pragma warning restore 612, 618
        }
    }
}
