// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RFIDify.Database;

#nullable disable

namespace RFIDify.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("RFIDify.RFID.Data.RFIDTag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("SpotifyId", "RFIDify.RFID.Data.RFIDTag.SpotifyId#SpotifyId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Id")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Type")
                                .HasColumnType("INTEGER");
                        });

                    b.HasKey("Id");

                    b.ToTable("RFIDs");
                });

            modelBuilder.Entity("RFIDify.Spotify.Data.SpotifyAccessToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Token");

                    b.ToTable("SpotifyAccessToken");
                });

            modelBuilder.Entity("RFIDify.Spotify.Data.SpotifyAuthorizationState", b =>
                {
                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("State");

                    b.ToTable("SpotifyAuthorizationState");
                });

            modelBuilder.Entity("RFIDify.Spotify.Data.SpotifyCredentials", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientSecret")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("SpotifyCredentials");
                });

            modelBuilder.Entity("RFIDify.Spotify.Data.SpotifyRefreshToken", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Token");

                    b.ToTable("SpotifyRefreshToken");
                });
#pragma warning restore 612, 618
        }
    }
}
